version: '3.3'

services:
  db:
    image: mysql:8.0.32
    container_name: nsdocs_db
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=nsdocs_consumption
      - TZ=America/Sao_Paulo
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/ddl.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./scripts/dml.sql:/docker-entrypoint-initdb.d/2_data.sql
      - ./scripts:/home/scripts
    ports:
      - "3366:3306"
    command:
      - '--skip-log-bin'
      - '--default-authentication-plugin=mysql_native_password'
      - '--sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
    networks:
      - nsdocs-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 5s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Messaging port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - nsdocs-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nsdocs_api
    environment:
      - DATABASE_URL=mysql://root:@db:3306/nsdocs_consumption
      - PORT=3000
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=nsdocs_consumption
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DOCUMENTS_QUEUE=documents_queue
      - MAX_RECONNECT_ATTEMPTS=5
      - RECONNECT_DELAY=5000
    ports:
      - "3001:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - nsdocs-network
    restart: unless-stopped

networks:
  nsdocs-network:
    driver: bridge

volumes:
  db_data:
  rabbitmq_data:
